### ISSUE TITLE
Exception in thread Thread 20:

### ISSUE THREAD

**Issue by ShukhratSh** [SKrisanski/FSCT#23]
Hi Krisanski,

I have 1 ha TLS point cloud that I want to perform a tree segmentation. I ran the code for 50x50m sample plot and result looks great. However, if I run it for 1 ha plot (19 GB), following error occurs.

$ python3 run.py
Current point cloud being processed:  /test/merged.las
Processing using  20 / 40  CPU cores.
Loading file... /test/merged.las
Saving file: ../test/merged_FSCT_output/working_point_cloud.las
Saved.
Pre-processing point cloud...
Exception in thread Thread-20:
Traceback (most recent call last):
  File "../.conda/envs/fsct_en/lib/python3.9/threading.py", line 950, in _bootstrap_inner
    self.run()
  File "../.conda/envs/fsct_en/lib/python3.9/threading.py", line 888, in run
    self._target(*self._args, **self._kwargs)
  File "../FSCT/scripts/preprocessing.py", line 103, in threaded_boxes
    np.save(path + str(id_offset + i).zfill(7) + ".npy", box)
  File "<__array_function__ internals>", line 180, in save
  File "../.conda/envs/fsct_en/lib/python3.9/site-packages/numpy/lib/npyio.py", line 519, in save
    format.write_array(fid, arr, allow_pickle=allow_pickle,
  File "../.conda/envs/fsct_en/lib/python3.9/site-packages/numpy/lib/format.py", line 690, in write_array
Exception in thread Thread-15:
Exception in thread Thread-13:
 
Does it mean the cluster have not enough cores to to run the script for this huge data set? Do you know how to work around this error? Alternatively, I can split the dataset and run the code, but I am not sure how to deal with edge effects at the moment.

Thank you!

**Comment by SKrisanski** [comment]
Hi ShukratSh,
That's a tricky one since it's happened in a multi-threaded section of the code, so there is limited information about the actual exception. I'm somewhat guessing here, but could you have run out of storage on the cluster?

I'm gradually working on a big refactor of FSCT. It will make it scale up really easily and deal with those edge effects automatically. Not sure how long it will take me to finish it off, but in the meantime, splitting up point clouds into smaller chunks would be the easiest option.
All the best,
Sean

**Comment by ShukhratSh** [comment]
Hi SKriasanski,
I think you are right, this error doesn't occur with smaller size tiles.

Thank you,
Shukhrat
