### ISSUE TITLE
Installation requirement.txt file

### ISSUE THREAD

**Issue by NinhGhoster** [SKrisanski/FSCT#36]
Look like stuck at this step

<haninhn@rdl-isfurp:~/Downloads/FSCT-main$ pip install -r requirements.txt

Looking in links: https://download.pytorch.org/whl/torch_stable.html, https://pytorch-geometric.com/whl/torch-1.9.0+cu111.html
Collecting certifi==2021.10.8 (from -r requirements.txt (line 4))
  Using cached certifi-2021.10.8-py2.py3-none-any.whl (149 kB)
Collecting charset-normalizer==2.0.12 (from -r requirements.txt (line 5))
  Using cached charset_normalizer-2.0.12-py3-none-any.whl (39 kB)
Collecting colorama==0.4.4 (from -r requirements.txt (line 6))
  Using cached colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Collecting cycler==0.11.0 (from -r requirements.txt (line 7))
  Using cached cycler-0.11.0-py3-none-any.whl (6.4 kB)
Collecting Cython==0.29.28 (from -r requirements.txt (line 8))
  Using cached Cython-0.29.28-py2.py3-none-any.whl (983 kB)
Collecting fonttools==4.33.3 (from -r requirements.txt (line 9))
  Using cached fonttools-4.33.3-py3-none-any.whl (930 kB)
Collecting googledrivedownloader==0.4 (from -r requirements.txt (line 10))
  Using cached googledrivedownloader-0.4-py2.py3-none-any.whl (3.9 kB)
Collecting hdbscan==0.8.28 (from -r requirements.txt (line 11))
  Using cached hdbscan-0.8.28.tar.gz (5.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting idna==3.3 (from -r requirements.txt (line 12))
  Using cached idna-3.3-py3-none-any.whl (61 kB)
Collecting imageio==2.19.0 (from -r requirements.txt (line 13))
  Using cached imageio-2.19.0-py3-none-any.whl (3.4 MB)
Collecting importlib-metadata==4.11.3 (from -r requirements.txt (line 14))
  Using cached importlib_metadata-4.11.3-py3-none-any.whl (18 kB)
Collecting isodate==0.6.1 (from -r requirements.txt (line 15))
  Using cached isodate-0.6.1-py2.py3-none-any.whl (41 kB)
Requirement already satisfied: Jinja2==3.1.2 in /home/student.unimelb.edu.au/haninhn/miniconda3/envs/pdal/lib/python3.12/site-packages (from -r requirements.txt (line 16)) (3.1.2)
Collecting joblib==1.1.0 (from -r requirements.txt (line 17))
  Using cached joblib-1.1.0-py2.py3-none-any.whl (306 kB)
Collecting kiwisolver==1.4.2 (from -r requirements.txt (line 18))
  Using cached kiwisolver-1.4.2.tar.gz (96 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting laspy==2.1.2 (from -r requirements.txt (line 19))
  Using cached laspy-2.1.2.tar.gz (598 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting Markdown==3.3.7 (from -r requirements.txt (line 20))
  Using cached Markdown-3.3.7-py3-none-any.whl (97 kB)
Collecting MarkupSafe==2.1.1 (from -r requirements.txt (line 21))
  Using cached MarkupSafe-2.1.1.tar.gz (18 kB)
  Preparing metadata (setup.py) ... done
Collecting matplotlib==3.5.2 (from -r requirements.txt (line 22))
  Using cached matplotlib-3.5.2.tar.gz (35.2 MB)
  Preparing metadata (setup.py) ... done
Collecting mdutils==1.3.1 (from -r requirements.txt (line 23))
  Using cached mdutils-1.3.1.tar.gz (19 kB)
  Preparing metadata (setup.py) ... done
Collecting networkx==2.8 (from -r requirements.txt (line 24))
  Using cached networkx-2.8-py3-none-any.whl (2.0 MB)
Collecting numpy==1.22.3 (from -r requirements.txt (line 25))
  Using cached numpy-1.22.3.zip (11.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Traceback (most recent call last):
        File "/home/student.unimelb.edu.au/haninhn/miniconda3/envs/pdal/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/student.unimelb.edu.au/haninhn/miniconda3/envs/pdal/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/student.unimelb.edu.au/haninhn/miniconda3/envs/pdal/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 112, in get_requires_for_build_wheel
          backend = _build_backend()
                    ^^^^^^^^^^^^^^^^
        File "/home/student.unimelb.edu.au/haninhn/miniconda3/envs/pdal/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
          obj = import_module(mod_path)
                ^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/student.unimelb.edu.au/haninhn/miniconda3/envs/pdal/lib/python3.12/importlib/__init__.py", line 90, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1304, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1325, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 929, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 994, in exec_module
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "/tmp/pip-build-env-xln2m_pv/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 16, in <module>
          import setuptools.version
        File "/tmp/pip-build-env-xln2m_pv/overlay/lib/python3.12/site-packages/setuptools/version.py", line 1, in <module>
          import pkg_resources
        File "/tmp/pip-build-env-xln2m_pv/overlay/lib/python3.12/site-packages/pkg_resources/__init__.py", line 2172, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
(pdal) haninhn@rdl-isfurp:~/Downloads/FSCT-main$>

**Comment by NinhGhoster** [comment]
Use ```conda install -c conda-forge hdbscan=0.8.28```command to solve this.
