### ISSUE TITLE
Error while loading run.py

### ISSUE THREAD

**Issue by Kostassan** [SKrisanski/FSCT#40]
I get this error window when trying to run  the run.py 

![image](https://github.com/SKrisanski/FSCT/assets/45093350/2b2db889-19f6-4265-a15a-05bee5bc9b7f)

**Comment by Kostassan** [comment]
This is also the error in the console 


C:\Users\ksideris\Documents\FSCT-main\scripts>python run.py
Traceback (most recent call last):
  File "C:\Users\ksideris\Documents\FSCT-main\scripts\run.py", line 1, in <module>
    from run_tools import FSCT, directory_mode, file_mode
  File "C:\Users\ksideris\Documents\FSCT-main\scripts\run_tools.py", line 2, in <module>
    from inference import SemanticSegmentation
  File "C:\Users\ksideris\Documents\FSCT-main\scripts\inference.py", line 3, in <module>
    import torch_geometric
  File "C:\Users\ksideris\AppData\Local\anaconda3\envs\FSCT\lib\site-packages\torch_geometric\__init__.py", line 5, in <module>
    import torch_geometric.data
  File "C:\Users\ksideris\AppData\Local\anaconda3\envs\FSCT\lib\site-packages\torch_geometric\data\__init__.py", line 1, in <module>
    from .data import Data
  File "C:\Users\ksideris\AppData\Local\anaconda3\envs\FSCT\lib\site-packages\torch_geometric\data\data.py", line 8, in <module>
    from torch_sparse import coalesce, SparseTensor
  File "C:\Users\ksideris\AppData\Local\anaconda3\envs\FSCT\lib\site-packages\torch_sparse\__init__.py", line 19, in <module>
    torch.ops.load_library(spec.origin)
  File "C:\Users\ksideris\AppData\Local\anaconda3\envs\FSCT\lib\site-packages\torch\_ops.py", line 255, in load_library
    ctypes.CDLL(path)
  File "C:\Users\ksideris\AppData\Local\anaconda3\envs\FSCT\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 127] The specified procedure could not be found
